# Generated by Django 4.2.13 on 2024-07-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazbin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelrooms',
            old_name='numder',
            new_name='number',
        ),
    ]
