# Generated by Django 4.2.14 on 2024-07-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazbin', '0003_client_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
