# Generated by Django 4.2.14 on 2024-07-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazbin', '0006_alter_client_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
